extends Node

@warning_ignore("unused_signal")
signal game_mode_changed(mode: Types.GameMode)
@warning_ignore("unused_signal")
signal card_clicked()
@warning_ignore("unused_signal")
signal card_error()

@warning_ignore("unused_signal")
signal card_destroy_requested(card:CardUI)
@warning_ignore("unused_signal")
signal discard_requested()
@warning_ignore("unused_signal")
signal card_played(card:CardUI)
@warning_ignore("unused_signal")
signal reshuffled_discard_pile()

@warning_ignore("unused_signal")
signal player_pause_state_changed()

@warning_ignore("unused_signal")
signal die_requested()
@warning_ignore("unused_signal")
signal spawn_requested()
@warning_ignore("unused_signal")
signal jump_requested()
@warning_ignore("unused_signal")
signal turn_around_requested()
@warning_ignore("unused_signal")
signal speed_requested(factor:float, duration:float)
@warning_ignore("unused_signal")
signal block_requested(placeholder: Placeholder)
@warning_ignore("unused_signal")
signal block_placed(block)


@warning_ignore("unused_signal")
signal player_died()
@warning_ignore("unused_signal")
signal player_respawned(player)

@warning_ignore("unused_signal")
signal checkpoint_requested()

@warning_ignore("unused_signal")
signal end_card_collected()
@warning_ignore("unused_signal")
signal tick()
@warning_ignore("unused_signal")
signal level_ended()
@warning_ignore("unused_signal")
signal game_ended()
@warning_ignore("unused_signal")
signal camera_toggled(mode:Types.CameraMode)
@warning_ignore("unused_signal")
signal global_void_expanded()
@warning_ignore("unused_signal")
signal new_void_cell(cell: Vector2i)
@warning_ignore("unused_signal")
signal in_danger()
@warning_ignore("unused_signal")
signal not_in_danger()


@warning_ignore("unused_signal")
signal restart_requested()
@warning_ignore("unused_signal")
signal close_menu_requested()
